# Generated by Django 4.2.5 on 2023-10-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_colorattribute_sizeattribute_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeattribute',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
